# -*- mode: ruby -*-
# vi: set ft=ruby :
# Author: Jorge Pereira <jpereira@freeradius.org>
# Desc: FreeBSD image ready to build the FreeBSD v3
#

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.1-STABLE"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    config.vm.hostname = "vm-freebsd01"
    config.vm.guest = :freebsd
    config.vm.boot_timeout = 60
    
    config.ssh.shell = "bash"
    config.ssh.host = "localhost"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.ssh.insert_key = false
#     vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "shell", inline: "echo hello", privileged: false
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
    service sshd restart

    portsnap fetch
    portsnap extract

    pkg update
    yes | pkg install vim htop sshfs fusefs-sshfs bash coreutils gdb clang portmaster

    make -C /usr/ports/net/freeradius3/

    echo "vfs.usermount=1" >> /etc/sysctl.conf
    sysrc kld_list+=fuse
    kldload fuse
    echo 'fusefs_enable="YES"' >> /etc/rc.conf

    devfs ruleset 10
    devfs rule add path 'fuse*' mode 666
  SHELL
end
